### ISSUE TITLE
Unable to download model weights

### ISSUE THREAD

**Issue by york-yan** [trinhvg/MSBP_Net#1]
I can't find the weights after opening the webpage. Could you please provide a new download link? Thank you very much.

**Comment by trinhvg** [comment]
Hello, We moved to another university so all the old content on the Google Drive has been gone. 
I can't find all the weight of comparative models in a short amount of time. However, I updated our MSBP models.
Thank you for your interest in our work. Cheers.

Model weights obtained from training MSBP here:

[Colon checkpoint](https://drive.google.com/drive/folders/129euzr7hZ3x99JaaSn6gWMdfdJiCbFC4?usp=drive_link)
[Prostate checkpoint](https://drive.google.com/drive/folders/1Hbbx2pUXcgEPnTvJoIcpXZ7BSaXQ7oWI?usp=drive_link)

**Comment by york-yan** [comment]
Good job, thanks very much!

**Comment by trinhvg** [comment]
Updated links.
